# -----------------------------------------------------
#   БАЗОВАЯ КОНФИГУРАЦИЯ HYPRLOCK
# -----------------------------------------------------

# === ФОН ===
background {
    # Путь к вашему фоновому изображению.
    # Если указать 'screenshot', hyprlock сделает скриншот рабочего стола и использует его.
    path = ~/.config/hypr/back.png
}

# === ПОЛЕ ВВОДА ПАРОЛЯ ===
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33 # Размер точек, скрывающих пароль
    dots_spacing = 0.15 # Расстояние между точками
    dots_center = true
    dots_rounding = -1 # -1 для идеальных кругов
    outer_color = rgb(151515)
    inner_color = rgb(200, 200, 200)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    placeholder_text = <i>Пароль...</i> # Текст, когда поле пустое
    hide_input = false
    rounding = -1 # -1 для максимального скругления
    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34) # Цвет при неверном вводе
    fail_text = <i>$FAIL</i> # Показать сообщение об ошибке ($FAIL заменяется текстом ошибки)
    fail_transition = 300 # Анимация при ошибке в мс

    position = 0, -20
    halign = center
    valign = center
}

# === ЧАСЫ ===
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%R")" # Обновление времени каждую секунду
    color = rgba(255, 255, 255, 0.9)
    font_size = 90
    font_family = Noto Sans
    
    position = 0, 80
    halign = center
    valign = center
}


